import { CalendarDateTime } from "@internationalized/date";

export type Semester = `${number}/${string}`;

export interface Class {
  classId: number, // map to class_id
  courseId: string;
  courseName: string;
  imageUrl?: string;
}

export interface TeachingClass extends Class {
  sections: number[]; // should be string, not exist
}

export interface Student {
  studentId: string;
  name: string;
  // email: string;
  section: number;
  group: string;
  imageUrl?: string;
  withdrawed: boolean;
  // TODO: think about this
  score: number;
  maxScore: number;
}

export interface Instructor {
  name: string;
  imageUrl?: string;
  email: string;
}

export interface ClassParticipants {
  instructors: Instructor[],
  teachingAssistants: TeachingAssistant[],
  students: Student[],
}

export interface TeachingAssistant {
  name: string;
  email: string;
  imageUrl?: string;
  leader: boolean;
}

export interface LabNotification {
  courseId: number;
  courseName: string;
  id: number;
  name: string;
  due: Date;
  maxScore: number;
}

export interface Testcase {
  input: string;
  output: string;
}

// TODO: map this to api type
export interface Question {
  number: number; // autogenerated, by index probably
  name: string;
  description: string;
  template: string; // predefine

  maxScore: number;
}

export interface StudentQuestion extends Question {
  submission?: {
    id: number;
    score: number;
    submittedAt: CalendarDateTime;
  };
}

export interface InstructorQuestion extends Question {
  answer: string;

  testCode: string; // wtf is the differences
  secretTestCode: string;

  testcases: Testcase[];
  secretTestCases: Testcase[];
}

type SupportedLanguage = string;

// ===========

export interface InstructorsAndTAs {
  instructors: Instructor[],
  teachingAssistant: TeachingAssistant[];
}

export interface ParticipatingClasses {
  studying: Class[];
  assisting: Class[];
}

export interface CreateStudentPayload {
  email: string,
  section: number,
  group?: string;
}

export interface UpdateStudentPayload {
  section?: number,
  group?: string,
  withdrawed?: boolean;
}

export interface CreateClassPayload {
  courseId: string;
  name: string;
  semester: Semester;
  image?: File;
  /**
   * Student csv file
   */
  students?: File;
}

export type UpdateClassPayload = Partial<CreateClassPayload>;





export type AssignmentStatus = "new" | "partially-completed" | "completed" | "lated" | "due-soon";

export type NearDueAssignment = {
  id: number;
  name: string;
  maxScore: number;
  due: CalendarDateTime; // RFC3339: 1996-12-19T16:39:57+07:00
  courseName: string;
  courseId: string;
};

export interface Assignment {
  id: number; // not exist yet

  additionalFileIds: number[];
  number: number;
  name: string;
  publish: CalendarDateTime; // @internationalized/date maybe
  due: CalendarDateTime; // RFC3339: 1996-12-19T16:39:57+07:00

  questionIds: number[];
  // maxScore: number; // This is computed property now
  languages: SupportedLanguage[]; // select at least one

  // should this be in StudentAssignment
  examMode: boolean;
  closeOnDue: boolean;
  assignedGroupIds: string[];
}

// TODO: omit a lot more
export interface StudentAssignment extends Assignment {
  score: number;
  status: AssignmentStatus;
}

export interface InstructorAssignment extends Assignment {
  // how do i get this?
  examPin: string; // 6 digit num
  showScoreOnLock: boolean; // hideOnClose ??? -> which mean we have some kind of state `isLocked` from the api

  testCode: string; // aka `testcase` | its like the one in 2024 class
  secretTestCode: string;
  questionIds: number[];
}

export type CreateAssignmentPayload = Omit<InstructorAssignment, "id" | "questionIds" | "additionalFileIds"> & {
  questions: InstructorQuestion[];
  additionalFiles: File[];
};

export type UpdateAssignmentPayload = Omit<CreateAssignmentPayload, "additionalFiles"> & {
  // WE CANT REMOVE FILE USING THIS REQ
  filesToAdd: File[];
};

export interface APIClient {
  students: {
    addToClass: (classId: number, payload: CreateStudentPayload) => Promise<void>,
    listByClass: (classId: number) => Promise<Student[]>,
    removeFromClass: (classId: number, studentId: string) => Promise<void>,
    update: (classId: number, studentId: string, data: UpdateStudentPayload) => Promise<void>,
    updateMany: (classId: number, studentIds: string[], data: UpdateStudentPayload) => Promise<void>,
  },
  classes: {
    getById: (classId: number) => Promise<Class>,
    listParticipatingBySemester: (semester: Semester) => Promise<ParticipatingClasses>,
    create: (payload: CreateClassPayload) => Promise<void>, // should it tho
    update: (classId: number, payload: UpdateClassPayload) => Promise<void>,
    // จารย์พลอยไม่เอา
    // delete: (classId: number) => Promise<void>,
  },
  sections: {
    getByClass: (classId: number) => Promise<number[]>;
  };
  semesters: {
    list: () => Promise<Semester[]>,
  },
  instructorsAndTAs: {
    listByClass: (classId: number) => Promise<InstructorsAndTAs>,
    addToClass: (classId: number, email: string) => Promise<void>,
    removeFromClass: (classId: number, email: string) => Promise<void>,
  },
  assignments: {
    listNearDue: () => Promise<NearDueAssignment[]>;
    listByClass: (classId: number) => Promise<StudentAssignment[]>;
    listByClassI: (classId: number) => Promise<InstructorAssignment[]>;

    // TODO: seperate this
    getById: (labId: number) => Promise<StudentAssignment>;
    getByIdI: (labId: number) => Promise<InstructorAssignment>;

    create: (classId: number, payload: CreateAssignmentPayload) => Promise<void>;
    update: (labId: number, payload: UpdateAssignmentPayload) => Promise<void>;
    // 

    removeFile: (fileId: number) => Promise<void>;
    // TODO: download it fr
    downloadFile: (fileId: number) => Promise<Blob>;
  };
  questions: {
    getById: (questionId: number) => Promise<StudentQuestion>;
    getByIdI: (questionId: number) => Promise<InstructorQuestion>;
  };
  supportedLanguages: {
    list: () => Promise<string[]>;
  };
  groups: {
    listByClassId: (classId: number) => Promise<string[]>;
  };
};
