import { CalendarDateTime } from "@internationalized/date";

export type Semester = `${number}/${string}`;

export interface Class {
  classId: number, // map to class_id
  courseId: string;
  courseName: string;
  imageUrl?: string;
}

export interface TeachingClass extends Class {
  sections: number[]; // should be string, not exist
}

export interface Student {
  studentId: string;
  name: string;
  // email: string;
  section: number;
  group: string;
  imageUrl?: string;
  withdrawed: boolean;
  // TODO: think about this
  score: number;
  maxScore: number;
}

export interface Instructor {
  name: string;
  imageUrl?: string;
  email: string; // TODO: tell backend to add this
}

export interface ClassParticipants {
  instructors: Instructor[],
  teachingAssistants: TeachingAssistant[],
  students: Student[],
}

export interface TeachingAssistant {
  name: string;
  email: string;  // TODO: tell backend to add this
  imageUrl?: string;
  leader: boolean;
}

export interface LabNotification {
  courseId: number;
  courseName: string;
  id: number;
  name: string;
  due: Date;
  maxScore: number;
}

export interface Testcase {
  input: string;
  output: string;
}

// TODO: map this to api type
export interface Question {
  number: number; // autogenerated, by index probably
  name: string;
  description: string;
  answer: string;
  template: string;
  score: number;

  testCode: string; // wtf is the differences
  secretTestCode: string;

  testcases: Testcase[];
  secretTestCases: Testcase[];
}

// const supportedLanguages = ["python", "java", "go", "js", "c", "ts"];
const supportedLanguages = ["python"];
type SupportedLanguage = typeof supportedLanguages[number];

export type LabStatus = "new" | "partially-completed" | "completed" | "lated" | "due-soon";

export interface Assignment {
  id: number;
  number: number;
  name: string;
  publish: CalendarDateTime; // @internationalized/date maybe
  due: CalendarDateTime; // RFC3339: 1996-12-19T16:39:57+07:00
  questionIds: number[];
  maxScore: number;
}

export interface StudentAssignment extends Assignment {
  score: number;
  status: LabStatus;
}

export type NearDueAssignment = Omit<Assignment, "number" | "publish" | "questionIds"> & {
  courseName: string;
  courseId: string;
};

// ===========

export interface InstructorsAndTAs {
  instructors: Instructor[],
  teachingAssistant: TeachingAssistant[];
}

export interface ParticipatingClasses {
  studying: Class[];
  assisting: Class[];
}

export interface CreateStudentPayload {
  email: string,
  section: number,
  group?: string;
}

export interface UpdateStudentPayload {
  section?: number,
  group?: string,
  withdrawed?: boolean;
}

export interface CreateClassPayload {
  courseId: string;
  name: string;
  semester: Semester;
  image?: File;
  /**
   * Student csv file
   */
  students?: File;
}

export type UpdateClassPayload = Partial<CreateClassPayload>;

export type CreateLabPayload = Omit<Assignment, "id" | "languages" | "questionIds" | "maxScore"> & {
  closeOnDue: boolean;
  showScoreOnLock: boolean; // hideOnClose ??? -> which mean we have some kind of state `isLocked` from the api

  template: string; // code that you give to the student

  languages: SupportedLanguage[]; // select at least one

  assignedGroupIds: string[];

  testCode: string; // code, like in 2024 class
  secretTestCode: string;

  questions: Question[];
  additionalFiles: File[];
};

export type UpdateLabPayload = Omit<CreateLabPayload, "additionalFiles"> & {
  // WE CANT REMOVE FILE USING THIS REQ
  filesToAdd: File[];
  examMode: boolean;
  examPin: string; // 6 digit num
};

export interface APIClient {
  students: {
    addToClass: (classId: number, payload: CreateStudentPayload) => Promise<void>,
    listByClass: (classId: number) => Promise<Student[]>,
    removeFromClass: (classId: number, studentId: string) => Promise<void>,
    update: (classId: number, studentId: string, data: UpdateStudentPayload) => Promise<void>,
    updateMany: (classId: number, studentIds: string[], data: UpdateStudentPayload) => Promise<void>,
  },
  classes: {
    getById: (classId: number) => Promise<Class>,
    listParticipatingBySemester: (semester: Semester) => Promise<ParticipatingClasses>,
    create: (payload: CreateClassPayload) => Promise<void>, // should it tho
    update: (classId: number, payload: UpdateClassPayload) => Promise<void>,
    // จารย์พลอยไม่เอา
    // delete: (classId: number) => Promise<void>,
  },
  sections: {
    getByClass: (classId: number) => Promise<number[]>;
  };
  semesters: {
    list: () => Promise<Semester[]>,
  },
  instructorsAndTAs: {
    listByClass: (classId: number) => Promise<InstructorsAndTAs>,
    addToClass: (classId: number, email: string) => Promise<void>,
    removeFromClass: (classId: number, email: string) => Promise<void>,
  },
  assignments: {
    // studentLab or not, cast it or seperate method?
    listNearDue: () => Promise<NearDueAssignment[]>;
    listByClass: (classId: number) => Promise<Assignment[]>;
    create: (classId: number, payload: CreateLabPayload) => Promise<void>;
    update: (labId: number, payload: UpdateLabPayload) => Promise<void>;
    getById: (labId: number) => Promise<Assignment>;

    removeFile: (labId: number, fileId: number) => Promise<void>;
    downloadFile: (labId: number, fileId: number) => Promise<void>;
  };
  questions: {
    getById: (questionId: number) => Promise<never>;

  };
};
