import { CalendarDateTime } from "@internationalized/date";

/**
 * Semester in format "YYYY/S" e.g. "2023/1"
 */
export type Semester = `${number}/${string}`;

export interface Class {
  /**
   * Mapped from backend `class_id`
   */
  classId: number;
  courseId: string;
  courseName: string;
  imageUrl?: string;
}

export interface TeachingClass extends Class {
  /**
   * List of section numbers
   * Note: Backend behavior for sections is inconsistent (number vs string)
   */
  sections: number[];
}

export interface Student {
  studentId: string;
  name: string;
  // email: string;
  section: number;
  group: string;
  imageUrl?: string;
  withdrawed: boolean;
  // TODO: think about this
  score: number;
  maxScore: number;
}

export interface Instructor {
  name: string;
  imageUrl?: string;
  email: string;
}

export interface ClassParticipants {
  instructors: Instructor[];
  teachingAssistants: TeachingAssistant[];
  students: Student[];
}

export interface TeachingAssistant {
  name: string;
  email: string;
  imageUrl?: string;
  leader: boolean;
}

export interface LabNotification {
  courseId: number;
  courseName: string;
  id: number;
  name: string;
  due: Date;
  maxScore: number;
}

export interface Testcase {
  input: string;
  output: string;
}

/**
 * Represents a logical question/problem within an assignment
 */
// TODO: map this to api type
export interface Question {
  id: number;
  /**
   * Autogenerated number, usually by index
   */
  number: number;
  name: string;
  description: string;
  /**
   * Starter code / template for the student
   */
  template: string; // predefine
  languages: SupportedLanguage[];

  maxScore: number;
}

export interface StudentQuestion extends Question {
  submission?: {
    id: number;
    score: number;
    submittedAt: CalendarDateTime;
  };
}

export interface InstructorQuestion extends Question {
  answer: string;

  /**
   * Test code used for grading
   * Note: Backend distinction between testCode and secretTestCode is specific to exam mode/settings
   */
  testCode: string;
  secretTestCode: string;

  testcases: Testcase[];
  secretTestCases: Testcase[];
}

export interface CreateInstructorQuestionPayload
  extends Omit<InstructorQuestion, "languages" | "id"> {
  languageIds: number[];
}

export type SupportedLanguage = {
  id: number; // e.g. 1, 2, 3
  name: string; // e.g. "C++", "Python 3"
};

// ===========

export interface InstructorsAndTAs {
  instructors: Instructor[];
  teachingAssistant: TeachingAssistant[];
}

export interface ParticipatingClasses {
  studying: Class[];
  assisting: Class[];
}

export interface CreateStudentPayload {
  email: string;
  section: number;
  group?: string;
}

export interface UpdateStudentPayload {
  section?: number;
  group?: string;
  withdrawed?: boolean;
}

export interface CreateClassPayload {
  courseId: number;
  name: string;
  semester: Semester;
  image?: File;
  /**
   * Student csv file
   */
  students?: File;
}

export type UpdateClassPayload = Partial<CreateClassPayload> & {
  // TODO: fix this?
  name: string;
  semester: Semester;
  courseId: number;
};

export type AssignmentStatus =
  | "new"
  | "partially-completed"
  | "completed"
  | "lated"
  | "due-soon";

export type NearDueAssignment = {
  id: number;
  name: string;
  maxScore: number;
  due: CalendarDateTime; // RFC3339: 1996-12-19T16:39:57+07:00
  courseName: string;
  courseId: string;
};

export interface Assignment {
  id: number;
  number: number;
  name: string;
  publish: CalendarDateTime;
  due: CalendarDateTime;
}

export interface AssignmentDetails {
  questionIds: number[];
  additionalFileIds: number[];
  examMode: boolean;
  closeOnDue: boolean;
  assignedGroupIds: string[];
}

export interface InstructorAssignmentDetailsFields {
  examPin: string;
  showScoreOnLock: boolean;
  testCode: string;
  secretTestCode: string;
}

// TODO: omit a lot more
export interface StudentAssignment extends Assignment {
  score: number;
  status: AssignmentStatus;
}

export interface StudentAssignmentDetails
  extends StudentAssignment,
    AssignmentDetails {
  questions: StudentQuestion[];
}

export type InstructorAssignment = Assignment;

export interface InstructorAssignmentDetails
  extends InstructorAssignment,
    AssignmentDetails,
    InstructorAssignmentDetailsFields {
  questions: InstructorQuestion[];
}

export interface QuestionSubmissionPayload {
  questionId: number;
  languageId: number;
  code: string;
}

export type CreateAssignmentPayload = Omit<InstructorAssignment, "id"> & {
  // Required fields for creation
  examPin: string;
  showScoreOnLock: boolean;
  testCode: string;
  secretTestCode: string;
  examMode: boolean;
  closeOnDue: boolean;
  assignedGroupIds: string[];
  questions: CreateInstructorQuestionPayload[];
};

export type UpdateAssignmentPayload = Partial<CreateAssignmentPayload>;

export interface CodePage {
  // ?????
  pageName: string;
  content: string;
}

export interface SubmissionResult {
  public: PublicTestcaseResult[];
  secret: SecretTestcaseResult[];
}

export interface PublicTestcaseResult {
  input: string; // TODO: request output if ui need it
  expectedOutput: string | null; // ????
  message: string;
  status: "pass" | "fail" | "pending";
}

export type SecretTestcaseResult = Omit<
  PublicTestcaseResult,
  "input" | "expectedOutput"
>;

export interface CodeSubmission {
  submissionId: number;
  code: CodePage[];
  language: SupportedLanguage;
}

export interface ClassProgress {
  done: number;
  maxLab: number;
}

export interface RankingInformation {
  rank: number;
  studentCount: number;
  /**
   * จะมีสมาชิก 10 ตัว แต่ละตัวจะบอกว่า  มีนักเรียนกี่คนตกอยู่ในช่วงคะแนนนั้นๆ
   * เช่น [1, 8, 3, ...] -> มี 1 คนที่ได้คะแนนในช่วง <10 , 8 คน ที่ได้คะแนน 10-20
   */
  rankGraph: number[];
  // TODO: idk what this is
  rankGraphPosition: number;
}

export interface ScoreInformation {
  score: number;
  maxScore: number;
  // TODO: idk what these 2 are
  ratioScore: number;
  maxRatioScore: number;
}

export interface Attendance {
  name: string;
  studentId: string;
  checkedInTime: Date;
  examName: string;
}

/**
 * API ที่มี, เอามาจากสเปค openapi
 *
 * ฟังก์ชั่นบางอันจะมีที่ชื่อคล้ายกันเช่น `api.assignments.listByClass` กับ `api.assignments.listByClassI`
 * อันที่ชื่อลงท้ายด้วย I หมายความว่าอันนั้นเป็น api สำหรับ Instructor/TA
 *
 * วิธีใช้ก็แค่ไป `import { api } from "@/lib/api";` มา
 */
export interface APIClient {
  students: {
    addToClass: (
      classId: number,
      payload: CreateStudentPayload
    ) => Promise<void>;
    listByClass: (classId: number) => Promise<Student[]>;
    removeFromClass: (classId: number, studentId: string) => Promise<void>;
    update: (
      classId: number,
      studentId: string,
      data: UpdateStudentPayload
    ) => Promise<void>;
    updateMany: (
      classId: number,
      studentIds: string[],
      data: UpdateStudentPayload
    ) => Promise<void>;
  };
  classes: {
    getById: (classId: number) => Promise<Class>;
    getProgressById: (classId: number) => Promise<ClassProgress>;
    getRankById: (classId: number) => Promise<RankingInformation>;
    listParticipatingBySemester: (
      semester: Semester
    ) => Promise<ParticipatingClasses>;
    create: (payload: CreateClassPayload) => Promise<void>; // should it tho
    update: (classId: number, payload: UpdateClassPayload) => Promise<void>;
    // จารย์พลอยไม่เอา
    // delete: (classId: number) => Promise<void>,
  };
  sections: {
    /**
     * ลิสต์ว่าใน class นั้นมี section อะไรบ้าง
     */
    getByClass: (classId: number) => Promise<number[]>;
  };
  semesters: {
    /**
     * List all semesters for the current user
     */
    list: () => Promise<Semester[]>;
  };
  instructorsAndTAs: {
    listByClass: (classId: number) => Promise<InstructorsAndTAs>;
    addToClass: (classId: number, email: string) => Promise<void>;
    removeFromClass: (classId: number, email: string) => Promise<void>;
  };

  assignments: {
    listNearDue: () => Promise<NearDueAssignment[]>;
    listByClass: (classId: number) => Promise<StudentAssignment[]>;
    listByClassI: (classId: number) => Promise<InstructorAssignment[]>;

    getById: (labId: number) => Promise<StudentAssignmentDetails>;
    getByIdI: (labId: number) => Promise<InstructorAssignmentDetails>;

    create: (
      classId: number,
      payload: CreateAssignmentPayload
    ) => Promise<void>;
    update: (labId: number, payload: UpdateAssignmentPayload) => Promise<void>;

    attachFile: (assignmentId: number, file: File) => Promise<void>;
    removeFile: (fileId: number) => Promise<void>;
    downloadFile: (fileId: number) => Promise<Blob>;
  };
  questions: {
    getById: (questionId: number) => Promise<StudentQuestion>;
    getByIdI: (questionId: number) => Promise<InstructorQuestion>;

    submit: (
      questionId: number,
      languageId: number,
      codes: CodePage[]
    ) => Promise<{ submissionId: number }>;
    getSubmission: (questionId: number) => Promise<CodeSubmission | null>;
    requestGrade: (submissionId: number) => Promise<void>;
    getSubmissionResult: (submissionId: number) => Promise<SubmissionResult>;
  };
  supportedLanguages: {
    list: () => Promise<SupportedLanguage[]>;
  };
  groups: {
    listByClassId: (classId: number) => Promise<string[]>;
  };
  exam: {
    // TODO: i will manage this state
    checkin: (examId: string, pin: string) => Promise<void>;
    isCheckedin: (examId: string) => Promise<boolean>;
    
    /**
     * @returns url ของรูป qrcode 
     */
    createQrcode: (mode: "checkin" | "checkout") => Promise<URL>;

    // TODO: no api yet
    listAttendance: (examId: string) => Promise<Attendance[]>;

    getPinByAssignmentId: (assignmentId: number) => Promise<string>;
  };
  testCode: {
    // TODO: rename this
    getById: (testCodeId: number) => Promise<string>;
  };
  testcase: {
    // this is for Mutilanguage testcase
    // TODO: rename this
    listByQuestionId: (
      testCodeId: number
    ) => Promise<{ public: Testcase[]; secret: Testcase[] }>;
  };
  server: {
    /**
     * เอาไว้ ping backend เผื่อล่ม
     * TODO: แสดงข้อความว่าล่ม
     */
    ping: () => Promise<void>;
  };
}
