FROM node:21 AS build

WORKDIR /app

# ติดตั้ง dependencies
COPY grader-frontend/package.json grader-frontend/package-lock.json ./
RUN npm install

# คัดลอกไฟล์ configuration
COPY .eslintrc.js ./
COPY next.config.js ./

# คัดลอก source code
COPY grader-frontend/. .
#  คัดลอก .env ที่สร้างไว้จาก GitHub Workflow
# COPY ../.env .env

RUN npm run build --verbose

# STEP 2: Serve with nginx
FROM nginx:alpine

# ลบ default nginx index page
RUN rm -rf /usr/share/nginx/html/*

# คัดลอก build ที่ถูกสร้างจาก step แรก
COPY --from=build /app/build /usr/share/nginx/html

# เพิ่ม nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]