FROM node:21 AS build

WORKDIR /app

COPY grader-frontend/package.json grader-frontend/package-lock.json ./
RUN npm ci --verbose

COPY grader-frontend/. . 
COPY grader-frontend/.env .env

RUN npm run build --verbose

FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
