version: "3.8"

services:
  authenticator:
    image: ghcr.io/cu-devclub/cugrader/auth:latest
    container_name: authenticator
    ports:
      - "6000:6000"
    environment:
      - SERVICE_ENV=production
      - CERT_PATH=/etc/ssl/auth/fullchain.pem
      - KEY_PATH=/etc/ssl/auth/privkey.pem
    volumes:
      - /home/ubuntu/ssl/auth:/etc/ssl/auth:ro

  backend:
    image: ghcr.io/cu-devclub/cugrader/backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - SERVICE_ENV=production
    depends_on:
      - yugabytedb
      - rabbitmq

  frontend:
    image: ghcr.io/cu-devclub/cugrader/frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=60

  minio:
    image: minio/minio:latest
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopassword
    volumes:
      - ./volume:/data
    command: server --address ":8001" --console-address ":8000" /data
    restart: always

  yugabytedb:
    image: yugabytedb/yugabyte
    container_name: yugabyte
    ports:
      - "7000:7000"
      - "9000:9000"
      - "15433:15433"
      - "5433:5433"
    environment:
      YSQL_USER: yugabyte
      YSQL_PASSWORD: yugabyte
    volumes:
      - yugabyte_data:/home/yugabyte/yb_data
    command: >
      bin/yugabyted start
      --base_dir=/home/yugabyte/yb_data
      --background=false
    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672"  
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  yugabyte_data:
  rabbitmq_data: