CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "user" (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    picture VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "student" (
    user_id INT PRIMARY KEY REFERENCES "user"(id) ON DELETE CASCADE,
    student_id VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "teacher" (
    user_id INT PRIMARY KEY REFERENCES "user"(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "admin" (
    user_id INT PRIMARY KEY REFERENCES "user"(id) ON DELETE CASCADE,
    added_by INT REFERENCES "user"(id) ON DELETE SET NULL,
    is_superadmin BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "picture" (
    id SERIAL PRIMARY KEY,
    path VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "class" (
    id SERIAL PRIMARY KEY,
    course_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    semester INT NOT NULL,
    year INT NOT NULL,
    picture_id INT REFERENCES "picture"(id) ON DELETE SET NULL,
    creater_user_id INT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS "class_assistant" (
    id SERIAL PRIMARY KEY,
    class_id INT NOT NULL REFERENCES "class"(id) ON DELETE CASCADE,
    user_id INT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    is_leader BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "section" (
    id SERIAL PRIMARY KEY,
    class_id INT NOT NULL REFERENCES "class"(id) ON DELETE CASCADE,
    section_number INT NOT NULL
);

CREATE TABLE IF NOT EXISTS "group" (
    id SERIAL PRIMARY KEY,
    class_id INT NOT NULL REFERENCES "class"(id) ON DELETE CASCADE,
    group_name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS "class_student" (
    id SERIAL PRIMARY KEY,
    class_id INT NOT NULL REFERENCES "class"(id) ON DELETE CASCADE,
    user_id INT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    section_id INT NOT NULL REFERENCES "section"(id) ON DELETE CASCADE,
    group_id INT REFERENCES "group"(id) ON DELETE CASCADE DEFAULT NULL,
    withdrawn BOOLEAN NOT NULL DEFAULT FALSE,
    withdrawn_at TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);