// Package gen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package gen

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Delete TA from class
	// (DELETE /TA)
	DeleteAssistantFromClass(c *gin.Context, params DeleteAssistantFromClassParams)
	// Add TA to class
	// (POST /TA)
	InsertAssistantToClass(c *gin.Context, params InsertAssistantToClassParams)
	// list ta and instructor by class
	// (GET /TA/{ClassId})
	GetAssistantsInClass(c *gin.Context, classId ClassId, params GetAssistantsInClassParams)

	// (DELETE /addfile/{AddFileId})
	DeleteAdditionalFile(c *gin.Context, addFileId AddFileId, params DeleteAdditionalFileParams)

	// (GET /addfile/{AddFileId})
	GetAdditionalFileContent(c *gin.Context, addFileId AddFileId, params GetAdditionalFileContentParams)

	// (GET /callback)
	GetCallback(c *gin.Context)

	// (POST /callback)
	GetUserDataFromGoogle(c *gin.Context)
	// partially edit class information
	// (PATCH /class)
	EditClass(c *gin.Context, params EditClassParams)
	// Create class
	// (POST /class)
	CreateClass(c *gin.Context, params CreateClassParams)

	// (GET /class/{ClassId})
	GetClassInformation(c *gin.Context, classId ClassId, params GetClassInformationParams)

	// (GET /classes/classes/{year-semester})
	GetClasses(c *gin.Context, yearSemester string, params GetClassesParams)

	// (GET /classes/semesters)
	GetSemesterOfUser(c *gin.Context, params GetSemesterOfUserParams)

	// (POST /code)
	SaveCodeToSystem(c *gin.Context, params SaveCodeToSystemParams)

	// (GET /code/{QuestionId})
	GetCodeFromSystem(c *gin.Context, questionId QuestionId, params GetCodeFromSystemParams)
	// get exam pin
	// (GET /exam_pin/{LabId})
	GetExaminationPin(c *gin.Context, labId LabId, params GetExaminationPinParams)

	// (GET /groups/{ClassId})
	GetGroupsInClass(c *gin.Context, classId ClassId, params GetGroupsInClassParams)
	// edit lab
	// (PATCH /lab)
	UpdateLab(c *gin.Context, params UpdateLabParams)
	// create lab
	// (POST /lab)
	CreateLab(c *gin.Context, params CreateLabParams)
	// lab detail
	// (GET /lab/{LabId})
	GetLabInformation(c *gin.Context, labId LabId, params GetLabInformationParams)

	// (GET /labs/{ClassId})
	GetLabsInClass(c *gin.Context, classId ClassId, params GetLabsInClassParams)

	// (GET /language)
	GetSystemSupportedLanguage(c *gin.Context)

	// (GET /login)
	RedirectUserToAuthenticationSystem(c *gin.Context)
	// get multi language testcase
	// (GET /multilang_testcase/{QuestionId})
	GetMultilanguageTestcaseInformation(c *gin.Context, questionId QuestionId, params GetMultilanguageTestcaseInformationParams)

	// (GET /near_due_date)
	GetNearDueDateLabs(c *gin.Context, params GetNearDueDateLabsParams)
	// getting image with picture id
	// (GET /picture/{PictureId})
	GetUserAndClassPicture(c *gin.Context, pictureId PictureId)

	// (GET /ping)
	TestPing(c *gin.Context)

	// (GET /question/{QuestionId})
	GetQuestionInformation(c *gin.Context, questionId QuestionId, params GetQuestionInformationParams)

	// (GET /result/{SubmissionId})
	GetGradedReult(c *gin.Context, submissionId SubmissionId, params GetGradedReultParams)

	// (GET /sections/{ClassId})
	GetSectionInClass(c *gin.Context, classId ClassId, params GetSectionInClassParams)
	// Delete student
	// (DELETE /students)
	DeleteStudentFromClass(c *gin.Context, params DeleteStudentFromClassParams)
	// Edit student info
	// (PATCH /students)
	EditStudentInClass(c *gin.Context, params EditStudentInClassParams)
	// Insert student
	// (POST /students)
	InsertStudentToClass(c *gin.Context, params InsertStudentToClassParams)
	// list student by class
	// (GET /students/{ClassId})
	GetStudentsIncClass(c *gin.Context, classId ClassId, params GetStudentsIncClassParams)

	// (POST /submit)
	GradeUsersCode(c *gin.Context, params GradeUsersCodeParams)

	// (POST /testcallback)
	UserForCreateTestUser(c *gin.Context)
	// get testcase
	// (GET /testcase/{TestCaseId})
	GetTestcaseInfomation(c *gin.Context, testCaseId TestCaseId, params GetTestcaseInfomationParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// DeleteAssistantFromClass operation middleware
func (siw *ServerInterfaceWrapper) DeleteAssistantFromClass(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteAssistantFromClassParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAssistantFromClass(c, params)
}

// InsertAssistantToClass operation middleware
func (siw *ServerInterfaceWrapper) InsertAssistantToClass(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params InsertAssistantToClassParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.InsertAssistantToClass(c, params)
}

// GetAssistantsInClass operation middleware
func (siw *ServerInterfaceWrapper) GetAssistantsInClass(c *gin.Context) {

	var err error

	// ------------- Path parameter "ClassId" -------------
	var classId ClassId

	err = runtime.BindStyledParameterWithOptions("simple", "ClassId", c.Param("ClassId"), &classId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ClassId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAssistantsInClassParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAssistantsInClass(c, classId, params)
}

// DeleteAdditionalFile operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdditionalFile(c *gin.Context) {

	var err error

	// ------------- Path parameter "AddFileId" -------------
	var addFileId AddFileId

	err = runtime.BindStyledParameterWithOptions("simple", "AddFileId", c.Param("AddFileId"), &addFileId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter AddFileId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteAdditionalFileParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAdditionalFile(c, addFileId, params)
}

// GetAdditionalFileContent operation middleware
func (siw *ServerInterfaceWrapper) GetAdditionalFileContent(c *gin.Context) {

	var err error

	// ------------- Path parameter "AddFileId" -------------
	var addFileId AddFileId

	err = runtime.BindStyledParameterWithOptions("simple", "AddFileId", c.Param("AddFileId"), &addFileId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter AddFileId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAdditionalFileContentParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdditionalFileContent(c, addFileId, params)
}

// GetCallback operation middleware
func (siw *ServerInterfaceWrapper) GetCallback(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCallback(c)
}

// GetUserDataFromGoogle operation middleware
func (siw *ServerInterfaceWrapper) GetUserDataFromGoogle(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUserDataFromGoogle(c)
}

// EditClass operation middleware
func (siw *ServerInterfaceWrapper) EditClass(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params EditClassParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.EditClass(c, params)
}

// CreateClass operation middleware
func (siw *ServerInterfaceWrapper) CreateClass(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateClassParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateClass(c, params)
}

// GetClassInformation operation middleware
func (siw *ServerInterfaceWrapper) GetClassInformation(c *gin.Context) {

	var err error

	// ------------- Path parameter "ClassId" -------------
	var classId ClassId

	err = runtime.BindStyledParameterWithOptions("simple", "ClassId", c.Param("ClassId"), &classId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ClassId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetClassInformationParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClassInformation(c, classId, params)
}

// GetClasses operation middleware
func (siw *ServerInterfaceWrapper) GetClasses(c *gin.Context) {

	var err error

	// ------------- Path parameter "year-semester" -------------
	var yearSemester string

	err = runtime.BindStyledParameterWithOptions("simple", "year-semester", c.Param("year-semester"), &yearSemester, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter year-semester: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetClassesParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClasses(c, yearSemester, params)
}

// GetSemesterOfUser operation middleware
func (siw *ServerInterfaceWrapper) GetSemesterOfUser(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSemesterOfUserParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSemesterOfUser(c, params)
}

// SaveCodeToSystem operation middleware
func (siw *ServerInterfaceWrapper) SaveCodeToSystem(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SaveCodeToSystemParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SaveCodeToSystem(c, params)
}

// GetCodeFromSystem operation middleware
func (siw *ServerInterfaceWrapper) GetCodeFromSystem(c *gin.Context) {

	var err error

	// ------------- Path parameter "QuestionId" -------------
	var questionId QuestionId

	err = runtime.BindStyledParameterWithOptions("simple", "QuestionId", c.Param("QuestionId"), &questionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter QuestionId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCodeFromSystemParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCodeFromSystem(c, questionId, params)
}

// GetExaminationPin operation middleware
func (siw *ServerInterfaceWrapper) GetExaminationPin(c *gin.Context) {

	var err error

	// ------------- Path parameter "LabId" -------------
	var labId LabId

	err = runtime.BindStyledParameterWithOptions("simple", "LabId", c.Param("LabId"), &labId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter LabId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetExaminationPinParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetExaminationPin(c, labId, params)
}

// GetGroupsInClass operation middleware
func (siw *ServerInterfaceWrapper) GetGroupsInClass(c *gin.Context) {

	var err error

	// ------------- Path parameter "ClassId" -------------
	var classId ClassId

	err = runtime.BindStyledParameterWithOptions("simple", "ClassId", c.Param("ClassId"), &classId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ClassId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGroupsInClassParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGroupsInClass(c, classId, params)
}

// UpdateLab operation middleware
func (siw *ServerInterfaceWrapper) UpdateLab(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateLabParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLab(c, params)
}

// CreateLab operation middleware
func (siw *ServerInterfaceWrapper) CreateLab(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateLabParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateLab(c, params)
}

// GetLabInformation operation middleware
func (siw *ServerInterfaceWrapper) GetLabInformation(c *gin.Context) {

	var err error

	// ------------- Path parameter "LabId" -------------
	var labId LabId

	err = runtime.BindStyledParameterWithOptions("simple", "LabId", c.Param("LabId"), &labId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter LabId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLabInformationParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLabInformation(c, labId, params)
}

// GetLabsInClass operation middleware
func (siw *ServerInterfaceWrapper) GetLabsInClass(c *gin.Context) {

	var err error

	// ------------- Path parameter "ClassId" -------------
	var classId ClassId

	err = runtime.BindStyledParameterWithOptions("simple", "ClassId", c.Param("ClassId"), &classId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ClassId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLabsInClassParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLabsInClass(c, classId, params)
}

// GetSystemSupportedLanguage operation middleware
func (siw *ServerInterfaceWrapper) GetSystemSupportedLanguage(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSystemSupportedLanguage(c)
}

// RedirectUserToAuthenticationSystem operation middleware
func (siw *ServerInterfaceWrapper) RedirectUserToAuthenticationSystem(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RedirectUserToAuthenticationSystem(c)
}

// GetMultilanguageTestcaseInformation operation middleware
func (siw *ServerInterfaceWrapper) GetMultilanguageTestcaseInformation(c *gin.Context) {

	var err error

	// ------------- Path parameter "QuestionId" -------------
	var questionId QuestionId

	err = runtime.BindStyledParameterWithOptions("simple", "QuestionId", c.Param("QuestionId"), &questionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter QuestionId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMultilanguageTestcaseInformationParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMultilanguageTestcaseInformation(c, questionId, params)
}

// GetNearDueDateLabs operation middleware
func (siw *ServerInterfaceWrapper) GetNearDueDateLabs(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNearDueDateLabsParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetNearDueDateLabs(c, params)
}

// GetUserAndClassPicture operation middleware
func (siw *ServerInterfaceWrapper) GetUserAndClassPicture(c *gin.Context) {

	var err error

	// ------------- Path parameter "PictureId" -------------
	var pictureId PictureId

	err = runtime.BindStyledParameterWithOptions("simple", "PictureId", c.Param("PictureId"), &pictureId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter PictureId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUserAndClassPicture(c, pictureId)
}

// TestPing operation middleware
func (siw *ServerInterfaceWrapper) TestPing(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TestPing(c)
}

// GetQuestionInformation operation middleware
func (siw *ServerInterfaceWrapper) GetQuestionInformation(c *gin.Context) {

	var err error

	// ------------- Path parameter "QuestionId" -------------
	var questionId QuestionId

	err = runtime.BindStyledParameterWithOptions("simple", "QuestionId", c.Param("QuestionId"), &questionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter QuestionId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetQuestionInformationParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetQuestionInformation(c, questionId, params)
}

// GetGradedReult operation middleware
func (siw *ServerInterfaceWrapper) GetGradedReult(c *gin.Context) {

	var err error

	// ------------- Path parameter "SubmissionId" -------------
	var submissionId SubmissionId

	err = runtime.BindStyledParameterWithOptions("simple", "SubmissionId", c.Param("SubmissionId"), &submissionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter SubmissionId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGradedReultParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGradedReult(c, submissionId, params)
}

// GetSectionInClass operation middleware
func (siw *ServerInterfaceWrapper) GetSectionInClass(c *gin.Context) {

	var err error

	// ------------- Path parameter "ClassId" -------------
	var classId ClassId

	err = runtime.BindStyledParameterWithOptions("simple", "ClassId", c.Param("ClassId"), &classId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ClassId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSectionInClassParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSectionInClass(c, classId, params)
}

// DeleteStudentFromClass operation middleware
func (siw *ServerInterfaceWrapper) DeleteStudentFromClass(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteStudentFromClassParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteStudentFromClass(c, params)
}

// EditStudentInClass operation middleware
func (siw *ServerInterfaceWrapper) EditStudentInClass(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params EditStudentInClassParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.EditStudentInClass(c, params)
}

// InsertStudentToClass operation middleware
func (siw *ServerInterfaceWrapper) InsertStudentToClass(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params InsertStudentToClassParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.InsertStudentToClass(c, params)
}

// GetStudentsIncClass operation middleware
func (siw *ServerInterfaceWrapper) GetStudentsIncClass(c *gin.Context) {

	var err error

	// ------------- Path parameter "ClassId" -------------
	var classId ClassId

	err = runtime.BindStyledParameterWithOptions("simple", "ClassId", c.Param("ClassId"), &classId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ClassId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStudentsIncClassParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStudentsIncClass(c, classId, params)
}

// GradeUsersCode operation middleware
func (siw *ServerInterfaceWrapper) GradeUsersCode(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GradeUsersCodeParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GradeUsersCode(c, params)
}

// UserForCreateTestUser operation middleware
func (siw *ServerInterfaceWrapper) UserForCreateTestUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UserForCreateTestUser(c)
}

// GetTestcaseInfomation operation middleware
func (siw *ServerInterfaceWrapper) GetTestcaseInfomation(c *gin.Context) {

	var err error

	// ------------- Path parameter "TestCaseId" -------------
	var testCaseId TestCaseId

	err = runtime.BindStyledParameterWithOptions("simple", "TestCaseId", c.Param("TestCaseId"), &testCaseId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter TestCaseId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTestcaseInfomationParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Authentication" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authentication")]; found {
		var Authentication WithJWT
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Authentication, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authentication", valueList[0], &Authentication, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Authentication: %w", err), http.StatusBadRequest)
			return
		}

		params.Authentication = &Authentication

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTestcaseInfomation(c, testCaseId, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.DELETE(options.BaseURL+"/TA", wrapper.DeleteAssistantFromClass)
	router.POST(options.BaseURL+"/TA", wrapper.InsertAssistantToClass)
	router.GET(options.BaseURL+"/TA/:ClassId", wrapper.GetAssistantsInClass)
	router.DELETE(options.BaseURL+"/addfile/:AddFileId", wrapper.DeleteAdditionalFile)
	router.GET(options.BaseURL+"/addfile/:AddFileId", wrapper.GetAdditionalFileContent)
	router.GET(options.BaseURL+"/callback", wrapper.GetCallback)
	router.POST(options.BaseURL+"/callback", wrapper.GetUserDataFromGoogle)
	router.PATCH(options.BaseURL+"/class", wrapper.EditClass)
	router.POST(options.BaseURL+"/class", wrapper.CreateClass)
	router.GET(options.BaseURL+"/class/:ClassId", wrapper.GetClassInformation)
	router.GET(options.BaseURL+"/classes/classes/:year-semester", wrapper.GetClasses)
	router.GET(options.BaseURL+"/classes/semesters", wrapper.GetSemesterOfUser)
	router.POST(options.BaseURL+"/code", wrapper.SaveCodeToSystem)
	router.GET(options.BaseURL+"/code/:QuestionId", wrapper.GetCodeFromSystem)
	router.GET(options.BaseURL+"/exam_pin/:LabId", wrapper.GetExaminationPin)
	router.GET(options.BaseURL+"/groups/:ClassId", wrapper.GetGroupsInClass)
	router.PATCH(options.BaseURL+"/lab", wrapper.UpdateLab)
	router.POST(options.BaseURL+"/lab", wrapper.CreateLab)
	router.GET(options.BaseURL+"/lab/:LabId", wrapper.GetLabInformation)
	router.GET(options.BaseURL+"/labs/:ClassId", wrapper.GetLabsInClass)
	router.GET(options.BaseURL+"/language", wrapper.GetSystemSupportedLanguage)
	router.GET(options.BaseURL+"/login", wrapper.RedirectUserToAuthenticationSystem)
	router.GET(options.BaseURL+"/multilang_testcase/:QuestionId", wrapper.GetMultilanguageTestcaseInformation)
	router.GET(options.BaseURL+"/near_due_date", wrapper.GetNearDueDateLabs)
	router.GET(options.BaseURL+"/picture/:PictureId", wrapper.GetUserAndClassPicture)
	router.GET(options.BaseURL+"/ping", wrapper.TestPing)
	router.GET(options.BaseURL+"/question/:QuestionId", wrapper.GetQuestionInformation)
	router.GET(options.BaseURL+"/result/:SubmissionId", wrapper.GetGradedReult)
	router.GET(options.BaseURL+"/sections/:ClassId", wrapper.GetSectionInClass)
	router.DELETE(options.BaseURL+"/students", wrapper.DeleteStudentFromClass)
	router.PATCH(options.BaseURL+"/students", wrapper.EditStudentInClass)
	router.POST(options.BaseURL+"/students", wrapper.InsertStudentToClass)
	router.GET(options.BaseURL+"/students/:ClassId", wrapper.GetStudentsIncClass)
	router.POST(options.BaseURL+"/submit", wrapper.GradeUsersCode)
	router.POST(options.BaseURL+"/testcallback", wrapper.UserForCreateTestUser)
	router.GET(options.BaseURL+"/testcase/:TestCaseId", wrapper.GetTestcaseInfomation)
}
