// Package gen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package gen

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AddFileId A unique identifier for a additional file, typically used to retrieve or reference a specific additional file in a system.
type AddFileId = int

// ClassId A unique identifier for a class, typically used to retrieve or reference a specific class in a system.
type ClassId = int

// ClassObject defines model for ClassObject.
type ClassObject struct {
	// ClassId A unique identifier for a class, typically used to retrieve or reference a specific class in a system.
	ClassId ClassId `json:"ClassId"`

	// PictureId A unique identifier for a picture, typically used to retrieve or reference an image in a system.
	PictureId PictureId `json:"PictureId"`

	// CourseId id of corse from reg
	CourseId   string `json:"course_id"`
	CourseName string `json:"course_name"`
}

// LabId A unique identifier for a lab, typically used to retrieve or reference a specific lab in a system.
type LabId = int

// LanguageId A unique identifier for a language, typically used to retrieve or reference an language in a system.
type LanguageId = int

// PictureId A unique identifier for a picture, typically used to retrieve or reference an image in a system.
type PictureId = int

// Pong defines model for Pong.
type Pong struct {
	Ping string `json:"ping"`
}

// QuestionId A unique identifier for a question, typically used to retrieve or reference a specific question in a system.
type QuestionId = int

// SubmissionId A unique identifier for a submission, typically used to retrieve or reference a specific submission in a system.
type SubmissionId = int

// TAEditBody defines model for TAEditBody.
type TAEditBody struct {
	// ClassId A unique identifier for a class, typically used to retrieve or reference a specific class in a system.
	ClassId ClassId `json:"ClassId"`

	// Email TA's email
	Email string `json:"email"`
}

// TestCaseId A unique identifier for a testcase, typically used to retrieve or reference a specific testcase in a system.
type TestCaseId = int

// WithJWT JWT token for authentication
type WithJWT = string

// LabEdit defines model for labEdit.
type LabEdit struct {
	// Addfiles Multiple additional files
	Addfiles   *[]openapi_types.File `json:"addfiles,omitempty"`
	AssignTo   *[]string             `json:"assign_to,omitempty"`
	CloseOnDue *bool                 `json:"close_on_due,omitempty"`

	// Due datetime
	Due         *string `json:"due,omitempty"`
	ExamMode    *bool   `json:"exam_mode,omitempty"`
	ExamPin     *int    `json:"exam_pin,omitempty"`
	LanguageIds *[]int  `json:"language_ids,omitempty"`
	Name        *string `json:"name,omitempty"`
	Number      *int    `json:"number,omitempty"`

	// Publish datetime
	Publish   *string `json:"publish,omitempty"`
	Questions *[]struct {
		Answer                  *string `json:"answer,omitempty"`
		Description             *string `json:"description,omitempty"`
		MultilangSecretTestcase *[]struct {
			Input  *string `json:"input,omitempty"`
			Output *string `json:"output,omitempty"`
		} `json:"multilang_secret_testcase,omitempty"`
		MultilangTestcase *[]struct {
			Input  *string `json:"input,omitempty"`
			Output *string `json:"output,omitempty"`
		} `json:"multilang_testcase,omitempty"`
		Name           *string `json:"name,omitempty"`
		Number         *int    `json:"number,omitempty"`
		Predefine      *string `json:"predefine,omitempty"`
		Score          *int    `json:"score,omitempty"`
		SecretTestcase *string `json:"secret_testcase,omitempty"`
		Testcase       *string `json:"testcase,omitempty"`
	} `json:"questions,omitempty"`
	SecretTestcase  *string `json:"secret_testcase,omitempty"`
	ShowScoreOnLock *bool   `json:"show_score_on_lock,omitempty"`
	Testcase        *string `json:"testcase,omitempty"`
}

// ErrBadRequest defines model for ErrBadRequest.
type ErrBadRequest struct {
	// HumanMessage A message for the user to understand the error
	HumanMessage string `json:"human_message"`
}

// ErrNotFound defines model for ErrNotFound.
type ErrNotFound struct {
	// HumanMessage A message for the user to understand the error
	HumanMessage string `json:"human_message"`
}

// ErrPermissionDecline defines model for ErrPermissionDecline.
type ErrPermissionDecline struct {
	// HumanMessage A message for the user to understand the error
	HumanMessage string `json:"human_message"`
}

// ErrPurrmissionDecline defines model for ErrPurrmissionDecline.
type ErrPurrmissionDecline struct {
	// HumanMessage A message for the cat to understand the error
	HumanMessage *string `json:"human_message,omitempty"`
}

// ErrServerIssue defines model for ErrServerIssue.
type ErrServerIssue struct {
	// DebugMessage A message for developers to understand the error
	DebugMessage string `json:"debug_message"`

	// HumanMessage A message for the user to understand the error
	HumanMessage string `json:"human_message"`
}

// ErrUnauthorized defines model for ErrUnauthorized.
type ErrUnauthorized struct {
	// HumanMessage A message for the user to understand the error
	HumanMessage string `json:"human_message"`
}

// DeleteAssistantFromClassParams defines parameters for DeleteAssistantFromClass.
type DeleteAssistantFromClassParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// InsertAssistantToClassParams defines parameters for InsertAssistantToClass.
type InsertAssistantToClassParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// GetAssistantsInClassParams defines parameters for GetAssistantsInClass.
type GetAssistantsInClassParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// DeleteAdditionalFileParams defines parameters for DeleteAdditionalFile.
type DeleteAdditionalFileParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// GetAdditionalFileContentParams defines parameters for GetAdditionalFileContent.
type GetAdditionalFileContentParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// GetUserDataFromGoogleJSONBody defines parameters for GetUserDataFromGoogle.
type GetUserDataFromGoogleJSONBody struct {
	// Credential encrypted data
	Credential string `json:"credential"`

	// Key key for decrypt data
	Key string `json:"key"`
}

// EditClassMultipartBody defines parameters for EditClass.
type EditClassMultipartBody struct {
	// ClassId A unique identifier for a class, typically used to retrieve or reference a specific class in a system.
	ClassId *ClassId `json:"ClassId,omitempty"`

	// CourseId course id according to reg cu
	CourseId int `json:"course_id"`

	// Image Class image file
	Image *openapi_types.File `json:"image,omitempty"`

	// Name Name of class
	Name string `json:"name"`

	// Semester Semester of class
	Semester string `json:"semester"`

	// Students Student csv file
	Students *openapi_types.File `json:"students,omitempty"`
}

// EditClassParams defines parameters for EditClass.
type EditClassParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// CreateClassMultipartBody defines parameters for CreateClass.
type CreateClassMultipartBody struct {
	// CourseId course id according to reg cu
	CourseId int `json:"course_id"`

	// Image Class image file
	Image *openapi_types.File `json:"image,omitempty"`

	// Name Name of class
	Name string `json:"name"`

	// Semester Semester of class
	Semester string `json:"semester"`

	// Students Student csv file
	Students *openapi_types.File `json:"students,omitempty"`
}

// CreateClassParams defines parameters for CreateClass.
type CreateClassParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// GetClassInformationParams defines parameters for GetClassInformation.
type GetClassInformationParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// GetClassesParams defines parameters for GetClasses.
type GetClassesParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// GetSemesterOfUserParams defines parameters for GetSemesterOfUser.
type GetSemesterOfUserParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// SaveCodeToSystemJSONBody defines parameters for SaveCodeToSystem.
type SaveCodeToSystemJSONBody struct {
	// LanguageId A unique identifier for a language, typically used to retrieve or reference an language in a system.
	LanguageId *LanguageId `json:"LanguageId,omitempty"`

	// QuestionId A unique identifier for a question, typically used to retrieve or reference a specific question in a system.
	QuestionId *QuestionId `json:"QuestionId,omitempty"`
	Code       []struct {
		Content  string `json:"content"`
		PageName string `json:"page_name"`
	} `json:"code"`
}

// SaveCodeToSystemParams defines parameters for SaveCodeToSystem.
type SaveCodeToSystemParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// GetCodeFromSystemParams defines parameters for GetCodeFromSystem.
type GetCodeFromSystemParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// GetExaminationPinParams defines parameters for GetExaminationPin.
type GetExaminationPinParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// GetGroupsInClassParams defines parameters for GetGroupsInClass.
type GetGroupsInClassParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// UpdateLabMultipartBody defines parameters for UpdateLab.
type UpdateLabMultipartBody struct {
	// LabId A unique identifier for a lab, typically used to retrieve or reference a specific lab in a system.
	LabId   *LabId   `json:"LabId,omitempty"`
	LabData *LabEdit `json:"lab_data,omitempty"`
}

// UpdateLabParams defines parameters for UpdateLab.
type UpdateLabParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// CreateLabMultipartBody defines parameters for CreateLab.
type CreateLabMultipartBody struct {
	// ClassId A unique identifier for a class, typically used to retrieve or reference a specific class in a system.
	ClassId *ClassId `json:"ClassId,omitempty"`
	LabData *LabEdit `json:"lab_data,omitempty"`
}

// CreateLabParams defines parameters for CreateLab.
type CreateLabParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// GetLabInformationParams defines parameters for GetLabInformation.
type GetLabInformationParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// GetLabsInClassParams defines parameters for GetLabsInClass.
type GetLabsInClassParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// GetMultilanguageTestcaseInformationParams defines parameters for GetMultilanguageTestcaseInformation.
type GetMultilanguageTestcaseInformationParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// GetNearDueDateLabsParams defines parameters for GetNearDueDateLabs.
type GetNearDueDateLabsParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// GetQuestionInformationParams defines parameters for GetQuestionInformation.
type GetQuestionInformationParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// GetGradedReultParams defines parameters for GetGradedReult.
type GetGradedReultParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// GetSectionInClassParams defines parameters for GetSectionInClass.
type GetSectionInClassParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// DeleteStudentFromClassJSONBody defines parameters for DeleteStudentFromClass.
type DeleteStudentFromClassJSONBody struct {
	// ClassId A unique identifier for a class, typically used to retrieve or reference a specific class in a system.
	ClassId ClassId `json:"ClassId"`

	// StudentId student id primary key
	StudentId string `json:"StudentId"`
}

// DeleteStudentFromClassParams defines parameters for DeleteStudentFromClass.
type DeleteStudentFromClassParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// EditStudentInClassJSONBody defines parameters for EditStudentInClass.
type EditStudentInClassJSONBody struct {
	// ClassId A unique identifier for a class, typically used to retrieve or reference a specific class in a system.
	ClassId ClassId `json:"ClassId"`

	// StudentId student id primary key
	StudentId string `json:"StudentId"`

	// Group group of student
	Group *string `json:"group,omitempty"`

	// Section section of student
	Section *int `json:"section,omitempty"`

	// Withdrawal is student withdrawn
	Withdrawal *bool `json:"withdrawal,omitempty"`
}

// EditStudentInClassParams defines parameters for EditStudentInClass.
type EditStudentInClassParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// InsertStudentToClassJSONBody defines parameters for InsertStudentToClass.
type InsertStudentToClassJSONBody struct {
	// ClassId A unique identifier for a class, typically used to retrieve or reference a specific class in a system.
	ClassId ClassId `json:"ClassId"`

	// Email student's email
	Email string `json:"email"`

	// Group group of student
	Group *string `json:"group,omitempty"`

	// Section section of student
	Section int `json:"section"`
}

// InsertStudentToClassParams defines parameters for InsertStudentToClass.
type InsertStudentToClassParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// GetStudentsIncClassParams defines parameters for GetStudentsIncClass.
type GetStudentsIncClassParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// GradeUsersCodeJSONBody defines parameters for GradeUsersCode.
type GradeUsersCodeJSONBody struct {
	// SubmissionId A unique identifier for a submission, typically used to retrieve or reference a specific submission in a system.
	SubmissionId SubmissionId `json:"SubmissionId"`
}

// GradeUsersCodeParams defines parameters for GradeUsersCode.
type GradeUsersCodeParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// UserForCreateTestUserJSONBody defines parameters for UserForCreateTestUser.
type UserForCreateTestUserJSONBody struct {
	// Credential email end with @chula.ac.th or @student chula.ac.th
	Credential string `json:"credential"`

	// Key unused
	Key *string `json:"key,omitempty"`
}

// GetTestcaseInfomationParams defines parameters for GetTestcaseInfomation.
type GetTestcaseInfomationParams struct {
	Authentication *WithJWT `json:"Authentication,omitempty"`
}

// DeleteAssistantFromClassJSONRequestBody defines body for DeleteAssistantFromClass for application/json ContentType.
type DeleteAssistantFromClassJSONRequestBody = TAEditBody

// InsertAssistantToClassJSONRequestBody defines body for InsertAssistantToClass for application/json ContentType.
type InsertAssistantToClassJSONRequestBody = TAEditBody

// GetUserDataFromGoogleJSONRequestBody defines body for GetUserDataFromGoogle for application/json ContentType.
type GetUserDataFromGoogleJSONRequestBody GetUserDataFromGoogleJSONBody

// EditClassMultipartRequestBody defines body for EditClass for multipart/form-data ContentType.
type EditClassMultipartRequestBody EditClassMultipartBody

// CreateClassMultipartRequestBody defines body for CreateClass for multipart/form-data ContentType.
type CreateClassMultipartRequestBody CreateClassMultipartBody

// SaveCodeToSystemJSONRequestBody defines body for SaveCodeToSystem for application/json ContentType.
type SaveCodeToSystemJSONRequestBody SaveCodeToSystemJSONBody

// UpdateLabMultipartRequestBody defines body for UpdateLab for multipart/form-data ContentType.
type UpdateLabMultipartRequestBody UpdateLabMultipartBody

// CreateLabMultipartRequestBody defines body for CreateLab for multipart/form-data ContentType.
type CreateLabMultipartRequestBody CreateLabMultipartBody

// DeleteStudentFromClassJSONRequestBody defines body for DeleteStudentFromClass for application/json ContentType.
type DeleteStudentFromClassJSONRequestBody DeleteStudentFromClassJSONBody

// EditStudentInClassJSONRequestBody defines body for EditStudentInClass for application/json ContentType.
type EditStudentInClassJSONRequestBody EditStudentInClassJSONBody

// InsertStudentToClassJSONRequestBody defines body for InsertStudentToClass for application/json ContentType.
type InsertStudentToClassJSONRequestBody InsertStudentToClassJSONBody

// GradeUsersCodeJSONRequestBody defines body for GradeUsersCode for application/json ContentType.
type GradeUsersCodeJSONRequestBody GradeUsersCodeJSONBody

// UserForCreateTestUserJSONRequestBody defines body for UserForCreateTestUser for application/json ContentType.
type UserForCreateTestUserJSONRequestBody UserForCreateTestUserJSONBody
