name: Build & Push Auth Service to GHCR

on:
  push:
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      
      - name: Generate hash for cache key
        id: hash
        run: echo "hash=$(sha256sum Auth/go.sum | cut -d ' ' -f1)" >> $GITHUB_OUTPUT   

      - name: Restore Go module cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-Auth-go-${{ steps.hash.outputs.hash }}
          restore-keys: |
            ${{ runner.os }}-Auth-go-

      - name: Tidy Go Modules
        working-directory: ./Auth
        run: go mod tidy

      - name: Build Go App
        working-directory: ./Auth
        run: go build -o main .

      - name: Generate .env from template
        working-directory: ./Auth
        run: cp .env.template .env
      
      - name: create-json (TESTING)
        id: create-json-testing
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "client_secrets.json"
          json: ${{ secrets.TEST_CLIENT_SECRETS }}
          dir: 'Auth/'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT_J || secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository name
        id: set_repo
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_LOWER=$REPO_LOWER" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Auth
          file: ./Auth/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}/auth:latest
            ghcr.io/${{ env.REPO_LOWER }}/auth:${{ github.sha }}
